### ISSUE TITLE
Update unsafe elliptic curve

### ISSUE THREAD

**Issue by nop33** [alephium/alephium-js#26]
https://github.com/alephium/alephium-js/blob/8fafcb8624a2da50e893d59cd033339d3320a0b1/lib/clique.ts#L21

Based on https://safecurves.cr.yp.to/, the curve of our choice is not safe (this site was recommended by the [`elliptic` npm](https://www.npmjs.com/package/elliptic) package that we are using).

Shouldn't we update it? If so, to which?

**Comment by polarker** [comment]
It's the same curve used by bitcoin, I would consider it still secure

**Comment by nop33** [comment]
Ah ok, thanks. Closing issue.
